import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Deniz Ozkan - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.avatarCircle}>
            <img className={styles.avatar} src="/images/deniz-ozkan.jpg" alt="Deniz Ozkan" width={90} height={90} />
          </div>
          <div className={styles.headerInfo}>
            <h1>Deniz Ozkan</h1>
            <h2>Software Engineer</h2>
          </div>
        </div>
        <div className={styles.bio}>
          <p>
            I am a lifelong student who tries to be a better version of himself every day. I enjoy working on front-end and back-end
            engineering, and I am highly passionate about turning difficult problems and creative ideas into things that live on the
            internet.
          </p>
        </div>
        <div className={styles.socials}>
          <a href="https://github.com/idnzozkan" title="GitHub" target="_blank" rel="noreferrer">
            <div className={styles.icon}>
              <img src="/icons/github.svg" alt="GitHub" width={20} height={20} />
            </div>
          </a>
          <a href="https://linkedin.com/in/idnzozkan" title="LinkedIn" target="_blank" rel="noreferrer">
            <div className={styles.icon}>
              <img src="/icons/linkedin.svg" alt="LinkedIn" width={20} height={20} />
            </div>
          </a>
          <a href="https://twitter.com/idnzozkan" title="Twitter" target="_blank" rel="noreferrer">
            <div className={styles.icon}>
              <img src="/icons/twitter.svg" alt="Twitter" width={20} height={20} />
            </div>
          </a>
          <a href="mailto:ibrahimdenizozkan@gmail.com" title="Email" target="_blank" rel="noreferrer">
            <div className={styles.icon}>
              <img src="/icons/email.svg" alt="Email" width={20} height={20} />
            </div>
          </a>
        </div>
      </main>
      <div className={styles.gradientLight}></div>
    </div>
  )
}
